name: Notify Main Repo

on: push

jobs:
  notify-main-project:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: majd-bitar/AutoSync
        event-type: update-submodules-event
